Repository trimstray/nginx-admins-handbook, pull requests merged in 2019-02, with the labels that each got.

#1 Update README.md
  README.md
Labels: Status: Closed, Status: Review Needed, Type: Bug

#3 Fix: typo
  README.md
Labels: Status: Review Needed, Type: Bug

#6 minor typo fix
  README.md
Labels: Status: Review Needed, Type: Bug

#7 imrprove deny access to hidden files/directories
  README.md
Labels: Status: Review Needed, Type: Enhancement
